import { NextResponse } from 'next/server';

export async function POST() {
  const script = `# ==============================================================================
# Enterprise RouterOS v7+ Hardened Security Protection Preset (2026 Standard)
# Generated by MT Management Next.js Security Engine
# Protection: WinBox/SSH Brute Force 3-Stage Auto-Blacklist, Open DNS Resolver DDoS Drop
# ==============================================================================

# 1. Address Lists Setup for Auto-Blacklisting
/ip firewall address-list
add list=brute_force_blacklist comment="Permanent 24h Brute-Force Blacklist"

# 2. Input Chain Filter Rules (Protection for Router Services)
/ip firewall filter
add chain=input action=drop connection-state=invalid comment="Drop Invalid Packets (Input)"
add chain=input action=drop src-address-list=brute_force_blacklist comment="Drop Brute-Force Blacklisted IPs (WinBox/SSH/Web/API)"

# 3-Stage Brute-Force Auto Blacklisting (WinBox 8291, SSH 22, Web 80/443, API 8728)
add chain=input action=add-src-to-address-list address-list=brute_force_blacklist address-list-timeout=1d protocol=tcp dst-port=22,8291,80,443,8728 src-address-list=bf_stage3 comment="Brute-Force Stage 3 -> Blacklist 24h"
add chain=input action=add-src-to-address-list address-list=bf_stage3 address-list-timeout=1m protocol=tcp dst-port=22,8291,80,443,8728 src-address-list=bf_stage2 comment="Brute-Force Stage 2 -> Stage 3"
add chain=input action=add-src-to-address-list address-list=bf_stage2 address-list-timeout=1m protocol=tcp dst-port=22,8291,80,443,8728 src-address-list=bf_stage1 comment="Brute-Force Stage 1 -> Stage 2"
add chain=input action=add-src-to-address-list address-list=bf_stage1 address-list-timeout=1m protocol=tcp dst-port=22,8291,80,443,8728 comment="Brute-Force Stage 1 Entry"

# 3. Prevent WAN Open DNS Resolver DDoS Amplification
add chain=input action=drop protocol=udp dst-port=53 in-interface-list=WAN comment="Drop Open DNS Resolver WAN Amplification Attack UDP"
add chain=input action=drop protocol=tcp dst-port=53 in-interface-list=WAN comment="Drop Open DNS Resolver WAN Amplification Attack TCP"

# 4. Display Completion Summary
:put "--------------------------------------------------------"
:put "RouterOS v7+ Hardened Protection Rules Applied!"
:put "Brute Force Auto Blacklist Active on ports: 22,8291,80,443,8728"
:put "--------------------------------------------------------"
`;

  return NextResponse.json({ script });
}
