import { NextRequest, NextResponse } from 'next/server';
import { executeOnRouter } from '@/lib/routeros';
import { FIREWALL_SERVICES } from '@/lib/firewall-services';

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { serviceKey, block, siteId } = body;

    const svc = FIREWALL_SERVICES[serviceKey];
    if (!svc) {
      return NextResponse.json({ error: 'Invalid firewall service key' }, { status: 400 });
    }

    await executeOnRouter(async (client) => {
      // 1. Ensure domain address-list entries exist
      const existingAddrList = await client.exec('/ip/firewall/address-list/print');
      for (const domain of svc.domains) {
        const found = existingAddrList.find((item) => item.list === svc.listName && item.address === domain);
        if (!found) {
          await client.exec('/ip/firewall/address-list/add', {
            list: svc.listName,
            address: domain,
            comment: `Auto-generated by Dashboard for ${svc.name}`,
          });
        }
      }

      // 2. Ensure filter rule exists
      const filterRules = await client.exec('/ip/firewall/filter/print');
      const rule = filterRules.find((r) => r.comment === svc.comment);

      if (rule) {
        await client.exec('/ip/firewall/filter/set', {
          '.id': rule['.id'],
          disabled: block ? 'no' : 'yes',
        });
      } else {
        await client.exec('/ip/firewall/filter/add', {
          chain: 'forward',
          action: 'drop',
          'dst-address-list': svc.listName,
          comment: svc.comment,
          disabled: block ? 'no' : 'yes',
        });
      }
    }, siteId);

    return NextResponse.json({ success: true, serviceKey, blocked: block });
  } catch (err: any) {
    return NextResponse.json({ error: err.message || 'Error toggling firewall rule' }, { status: 500 });
  }
}
