'use client';

import React, { useState } from 'react';
import { ShieldAlert, Code, CheckCircle, Lock, Copy } from 'lucide-react';

export default function FirewallPage() {
  const [showScriptModal, setShowScriptModal] = useState(false);
  const [copied, setCopied] = useState(false);

  const securityScript = `# ==============================================================================
# Enterprise RouterOS v7+ Hardened Security Protection Preset (2026 Standard)
# Generated by MT Management Next.js Security Engine
# Protection: WinBox/SSH Brute Force 3-Stage Auto-Blacklist, Open DNS Resolver DDoS Drop
# ==============================================================================

# 1. Address Lists Setup for Auto-Blacklisting
/ip firewall address-list
add list=brute_force_blacklist comment="Permanent 24h Brute-Force Blacklist"

# 2. Input Chain Filter Rules (Protection for Router Services)
/ip firewall filter
add chain=input action=drop connection-state=invalid comment="Drop Invalid Packets (Input)"
add chain=input action=drop src-address-list=brute_force_blacklist comment="Drop Brute-Force Blacklisted IPs (WinBox/SSH/Web/API)"

# 3-Stage Brute-Force Auto Blacklisting (WinBox 8291, SSH 22, Web 80/443, API 8728)
add chain=input action=add-src-to-address-list address-list=brute_force_blacklist address-list-timeout=1d protocol=tcp dst-port=22,8291,80,443,8728 src-address-list=bf_stage3 comment="Brute-Force Stage 3 -> Blacklist 24h"
add chain=input action=add-src-to-address-list address-list=bf_stage3 address-list-timeout=1m protocol=tcp dst-port=22,8291,80,443,8728 src-address-list=bf_stage2 comment="Brute-Force Stage 2 -> Stage 3"
add chain=input action=add-src-to-address-list address-list=bf_stage2 address-list-timeout=1m protocol=tcp dst-port=22,8291,80,443,8728 src-address-list=bf_stage1 comment="Brute-Force Stage 1 -> Stage 2"
add chain=input action=add-src-to-address-list address-list=bf_stage1 address-list-timeout=1m protocol=tcp dst-port=22,8291,80,443,8728 comment="Brute-Force Stage 1 Entry"

# 3. Prevent WAN Open DNS Resolver DDoS Amplification
add chain=input action=drop protocol=udp dst-port=53 in-interface-list=WAN comment="Drop Open DNS Resolver WAN Amplification Attack UDP"
add chain=input action=drop protocol=tcp dst-port=53 in-interface-list=WAN comment="Drop Open DNS Resolver WAN Amplification Attack TCP"

:put "--------------------------------------------------------"
:put "RouterOS v7+ Hardened Protection Rules Applied!"
:put "--------------------------------------------------------"
`;

  const handleCopyScript = () => {
    navigator.clipboard.writeText(securityScript);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-xl font-bold text-white tracking-tight flex items-center gap-2">
          <ShieldAlert className="w-6 h-6 text-rose-400" />
          <span>จัดการความปลอดภัย & บล็อกเว็บ (Firewall Hardening)</span>
        </h2>
        <p className="text-xs text-slate-400 mt-1">ป้องกันภัยคุกคาม Cyber, Brute-Force Attacks และบล็อกโซเชียลมีเดีย</p>
      </div>

      {/* Security Hardening Preset Banner */}
      <div className="p-6 rounded-2xl bg-gradient-to-r from-slate-950 via-indigo-950/60 to-slate-950 border border-indigo-500/30 shadow-xl space-y-4">
        <div className="flex items-center space-x-3">
          <div className="w-10 h-10 rounded-xl bg-indigo-500/20 text-indigo-400 flex items-center justify-center border border-indigo-500/30">
            <Lock className="w-5 h-5" />
          </div>
          <div>
            <h3 className="text-sm font-bold text-white">เกราะป้องกันความปลอดภัย RouterOS v7+ (2026 Hardened Protection Preset)</h3>
            <p className="text-xs text-slate-400">ป้องกัน Brute-force สุ่มรหัสผ่าน WinBox/SSH/Web, ดรอป Invalid Packets และป้องกัน DNS Amplification DDoS</p>
          </div>
        </div>

        <div className="flex flex-wrap items-center gap-3 pt-2">
          <button
            onClick={() => setShowScriptModal(true)}
            className="px-4 py-2 bg-slate-900 hover:bg-slate-800 text-slate-200 border border-slate-700 rounded-xl text-xs font-semibold flex items-center space-x-2 transition-all"
          >
            <Code className="w-4 h-4 text-indigo-400" />
            <span>ดูสคริปต์ RouterOS CLI</span>
          </button>
        </div>
      </div>

      {/* Script Modal */}
      {showScriptModal && (
        <div className="fixed inset-0 z-50 bg-slate-950/80 backdrop-blur-md flex items-center justify-center p-4">
          <div className="bg-slate-900 border border-slate-800 rounded-2xl max-w-2xl w-full p-6 space-y-4 shadow-2xl">
            <div className="flex items-center justify-between border-b border-slate-800 pb-3">
              <h3 className="font-bold text-sm text-white flex items-center gap-2">
                <Code className="w-4 h-4 text-indigo-400" />
                <span>สคริปต์ RouterOS v7 Hardened Security Preset</span>
              </h3>
              <button onClick={() => setShowScriptModal(false)} className="text-slate-400 hover:text-white text-lg">
                &times;
              </button>
            </div>

            <textarea
              readOnly
              value={securityScript}
              className="w-full h-72 p-4 bg-slate-950 font-mono text-xs text-sky-400 rounded-xl border border-slate-800 focus:outline-none"
            />

            <div className="flex justify-end space-x-3">
              <button
                onClick={() => setShowScriptModal(false)}
                className="px-4 py-2 bg-slate-800 text-slate-300 text-xs font-semibold rounded-xl"
              >
                ปิด
              </button>
              <button
                onClick={handleCopyScript}
                className="px-4 py-2 bg-indigo-600 hover:bg-indigo-700 text-white text-xs font-semibold rounded-xl flex items-center space-x-1.5 shadow-md"
              >
                {copied ? <CheckCircle className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                <span>{copied ? 'คัดลอกเรียบร้อยแล้ว!' : 'คัดลอกสคริปต์'}</span>
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
